### ISSUE TITLE
Establish Server

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#25]
- [x] Make a prototype SailsJS server
- [x] Use MongoDB
- [x] Going to have one endpoint that takes a JSON blob, that's it
- [x] Persist the JSON to MongoDB ~~S3 bucket~~ (Not sure about this since the client encodes the whole thing as a base 64 string)
- [x] Write a readme for starting this up

[SailsJS](https://sailsjs.com/)

**Comment by ianjennings** [comment]
When you run `sails new`, use `Empty`. We won't need the extra features Sails comes with.

Use `sails generate` to create your model, routes, etc, it's really helpful.
https://sailsjs.com/documentation/reference/command-line-interface/sails-generate

**Comment by ianjennings** [comment]
See #26

**Comment by mohammedsahl** [comment]
Link to [PR](https://github.com/MLH-Fellowship/babel-sandbox-server/pull/1) since its cross-repo

**Comment by wlawt** [comment]
Removing `Use Redis for sessions` from the current milestone task (not currently needed to have a basic MVP working). 

TODO:
- [ ] Use Redis for sessions

**Comment by wlawt** [comment]
### Task 3: Going to have one endpoint that takes a JSON blob, that's it
1. First, we should create a Controller (JSONController.js) `sails generate api JSON`
    - See [this doc](https://sailsjs.com/documentation/concepts/actions-and-controllers) on creating and using controllers
2. Create a model in `api/models/` (see how to create [models](https://sailsjs.com/documentation/concepts/models-and-orm/models)) with the following attributes:
    - id
    - Date created
    - Last edited 
    - The JSON stringified objected
    - _*There should be three models: for the Blob, Plugin, and Config_ 
        - Config should also include `forks: <Array>` and `forkedForm`  see #27

**The expected output:**
- We should have a Controller that will handle incoming JSON
- We should have a model with the necessary attributes

**Comment by wlawt** [comment]
### Task 4: Persist the JSON to MongoDB
1. Call the API endpoint via React using `Axios` pinging the api `localhost:1337/api/JSON` <- or something similar to that
2. Inside the `JSONController.js` we should use the `.create()` function on our model object to insert into MongoDB
    - See [this doc](https://sailsjs.com/documentation/reference/waterline-orm/models/create) for more info
    - See [this tutorial](https://jhtechservices.com/using-mongodb-and-sails-js-with-a-basic-one-to-many-association/) that does a brief walkthrough on inserting into MongoDB

The expected output: 
- We should be able to see a JSON stringified object in our MongoDB

**Comment by mohammedsahl** [comment]
Pinging to Axios is a front-end thing yeah (not something the backend should be worried about)? I'm currently using postman to make sure the endpoints work as expected. 

Also from today's stand-up @ianjennings and I decided it would be better to have [associations](https://sailsjs.com/documentation/concepts/models-and-orm/associations) between the blob and the associated plugin and configs. (ie Blob, Plugin and Config are their own model)

**Comment by wlawt** [comment]
Yeah, just throwing it in to consider the middleware needed.

**Comment by mohammedsahl** [comment]
Could I have an example JSON blob that I can work with? One with at least two different configs would be sick! I could write up my own but I feel it's better to leave the structure of the JSON up to the front-end peeps. Or anyone who can ensure that both ends are working with the same JSON blob

EDIT: Something like [this](http://www.objgen.com/json/models/etT) perhaps. It has fields for ID that will be calculated on the server-side. The actual request body will probably have everything in that example except for `dateCreated` and the `base64ID`s
